### ISSUE TITLE
Overlay should meet edges

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#106]
![Screen Shot 2021-05-26 at 7.13.45 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/98645afc-991d-40a9-9342-c67c301042e5)

**Comment by banhpete** [comment]
Overlay has been expanded.

See PR: https://github.com/Allied-Voices/alliedvoices/pull/111
