### ISSUE TITLE
Change backend data for Map from "Articles" to "Articles copy"

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#119]
In the Airtable

**Comment by SDC-LZC** [comment]
In the Airtable

**Comment by banhpete** [comment]
Changed 'Articles' to 'Articles (OLD)' and then 'Articles Copy' to 'Articles.

Update Alliedvoices accordingly.

See PR: https://github.com/Allied-Voices/alliedvoices/pull/133
