### ISSUE TITLE
Develop new landing page

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#122]
Design for landing page shown [here](https://www.figma.com/file/Ue1fW14sa8dNi63Zc1rGrf/Allied-Voices?node-id=1563%3A0)

**Comment by banhpete** [comment]
@SDC-LZC , @kw496 
Just some questions about this ticket:
- For this page, what stories of allyship and empowering stories should we pull from Airtable? Is it going to be random?
- Where would the 'Contribute' button take us to for now?

**Comment by SDC-LZC** [comment]
- For now maybe it could pull randomly
- Contribute button will not lead anywhere for right now --> will have to design + develop contribute flow
