### ISSUE TITLE
Take out "Source" as a filter in search

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#123]
**Will use this later when we are incorporating other sources of content (e.g. social media, user submissions)

![Screen Shot 2021-06-30 at 7.20.53 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/ed249b89-c4a0-4dd2-8689-01bc385092e2)

**Comment by banhpete** [comment]
Source filter was commented out of the code.

See PR: https://github.com/Allied-Voices/alliedvoices/pull/135
