### ISSUE TITLE
Take out "Incident Tags" as a filter in search

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#124]
**Will have to redesign this filter

![Screen Shot 2021-06-30 at 7.24.27 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/188073f2-2a9e-4d04-80a2-792700fc8a92)

**Comment by banhpete** [comment]
Incident Tags filter was commented out of the code.

See PR: https://github.com/Allied-Voices/alliedvoices/pull/135
