### ISSUE TITLE
Take out "Race" as a filter

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#125]
**Will have LGBTQ and more

![Screen Shot 2021-06-30 at 7.26.56 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/cc340919-3299-423a-8331-b35b88f41e2c)

**Comment by banhpete** [comment]
Race filter was commented out of the code.

See PR: https://github.com/Allied-Voices/alliedvoices/pull/135
