### ISSUE TITLE
Take out classifications for article

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#126]
**Will hide the classifications

![Screen Shot 2021-06-30 at 8.25.24 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/4e831f5f-e092-42c7-a988-e11064d77cad)

**Comment by banhpete** [comment]
Classifications removed.

See PR: https://github.com/Allied-Voices/alliedvoices/pull/137
