### ISSUE TITLE
Titles in sidebar do not match title of article + article

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#178]
I think there is a problem in the way the website is pulling data from Airtable

![Screen Shot 2021-12-13 at 2 51 05 PM](https://user-images.githubusercontent.com/53403068/145887166-1881a7fa-2a08-4cac-997c-83a843135271.png)

![Screen Shot 2021-12-13 at 4 48 26 PM](https://user-images.githubusercontent.com/53403068/145901496-bc4f551e-8304-4a15-8d94-7fcbda75fdc1.png)

![Screen Shot 2021-12-13 at 4 48 37 PM](https://user-images.githubusercontent.com/53403068/145901529-e7bb38be-1f3f-4f04-a47f-66483d1862fe.png)

![Screen Shot 2021-12-13 at 2 52 41 PM](https://user-images.githubusercontent.com/53403068/145901507-9f96983f-61b4-4f27-9e66-cf8a10bebbce.png)

**Comment by SDC-LZC** [comment]
<img width="994" alt="Screen Shot 2022-01-17 at 7 33 44 PM" src="https://user-images.githubusercontent.com/53403068/149855611-824cddbc-b60e-48cf-b4ff-3240bc127a75.png">

**Comment by Latecoder-hub** [comment]
I can't see this issue anymore, maybe we can close this?

**Comment by SDC-LZC** [comment]
I will upload some new articles so we can see it!
