### ISSUE TITLE
Set landing page location recommendation to "New York, New York"

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#55]

**Comment by SDC-LZC** [comment]
![Location input](https://user-images.githubusercontent.com/53403068/116927569-744c7c80-ac21-11eb-8fec-415d0e2f7971.png)

**Comment by SDC-LZC** [comment]
Note: We might change the landing page

**Comment by banhpete** [comment]
Default location is now New York.

See PR https://github.com/Allied-Voices/alliedvoices/pull/81
