### ISSUE TITLE
Certain map transitions from article to article are sudden

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#59]
It would be great if we could visually convey the distance from the user's display window to the article (outside of the user's display window)

Maybe a fly over to the article (to show direction + distance)

![Screen Shot 2021-05-03 at 2.22.20 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/7a1bd315-f273-40c5-a36f-11a7c986516c)

![Screen Shot 2021-05-03 at 2.22.31 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/bf1c5ecd-217e-4cdf-96ec-e79edc4470ce)

**Comment by banhpete** [comment]
Logic was added in to fly to a marker when clicked now if it is about 2 km away.

This changed was made in https://github.com/Allied-Voices/alliedvoices/pull/76.
