### ISSUE TITLE
Indicator for when an article is being displayed (in the reading display)

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#60]
Found myself clicking on the heart multiple times, unsure if it had been displayed in the reading display (would be nice if we can make transition clear)

Maybe make the icon bigger when clicked on? or show a flash in the reading display to show transition?

![Screen Shot 2021-05-03 at 2.32.40 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/a1c95fe1-1fe8-4e64-8048-e78b0472a06d)![Screen Shot 2021-05-03 at 2.32.55 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/a6b19f7c-fb95-4d4a-ad8d-759800cb42ae)

**Comment by banhpete** [comment]
The marker is now bigger when it's article is selected.

This change was made in this PR: https://github.com/Allied-Voices/alliedvoices/pull/76.
