### ISSUE TITLE
1. When hearts are close together and 2.clicking into the next article in the list the pop up box might not change

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#61]
![Screen Shot 2021-05-03 at 2.36.57 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/30b00089-59e1-4281-baba-fa0b1752f9a8)

**Comment by banhpete** [comment]
The pop up will now appear when any article is selected.

This change was made in the following PR: https://github.com/Allied-Voices/alliedvoices/pull/76
