### ISSUE TITLE
Change 1. incident icon to red dot 2. good deeds icon to green dot

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#66]

**Comment by banhpete** [comment]
Do we have an idea of what color to use, and their relative size? @SDC-LZC

**Comment by SDC-LZC** [comment]
- Drop shadow on the map
- No stroke + no drop shadow on the article list

**Comment by kw496** [comment]
In [Figma](https://www.figma.com/file/Ue1fW14sa8dNi63Zc1rGrf/Allied-Voices?node-id=1564%3A130): 

![green circles](https://user-images.githubusercontent.com/26206191/119747138-b13e1480-be57-11eb-885c-1d3dd2b0d768.png)

**Comment by banhpete** [comment]
Icons changed. 

See PR: https://github.com/Allied-Voices/alliedvoices/pull/113
