### ISSUE TITLE
change display tab to 1. Be overlay (vs. slide out) 2. Center map on point

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#68]
![Screen Shot 2021-05-14 at 12.15.59 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/b562852c-995c-47c5-8b57-56305a1ce74d)

**Comment by banhpete** [comment]
Article popup is now made an overlay. The marker will also now be at the center of the map (the part of it which is visible to the user).

See PR: https://github.com/Allied-Voices/alliedvoices/pull/101 and https://github.com/Allied-Voices/alliedvoices/pull/99
