### ISSUE TITLE
Change resources to be tiles as opposed to list

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#69]
Cards should include:
1. Image
2. Title
3. Source

**Comment by kw496** [comment]
In [Figma](https://www.figma.com/file/Ue1fW14sa8dNi63Zc1rGrf/Allied-Voices?node-id=1564%3A256): 

![Resource cards](https://user-images.githubusercontent.com/26206191/119747312-15f96f00-be58-11eb-8d4d-d420ef1d64df.png)

**Comment by banhpete** [comment]
Resource List changed to tiles.

See PR: https://github.com/Allied-Voices/alliedvoices/pull/131
