### ISSUE TITLE
Fix unknown miles away

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#71]
![Screen Shot 2021-05-13 at 1.49.34 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/8e908395-79ff-4584-ac44-cda254446874)

**Comment by banhpete** [comment]
The distance away from New York will now correctly show.

See PR https://github.com/Allied-Voices/alliedvoices/pull/83

@SDC-LZC Are we okay with showing '0 mi away'?

**Comment by banhpete** [comment]
If we want a new message instead '0 mi away' let's open a new issue instead, going to close this one.
