### ISSUE TITLE
Fix grammatical errors on landing page

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#73]
![Screen Shot 2021-05-03 at 3.06.48 PM.png](https://images.zenhubusercontent.com/5f1f9af5f2b598456a4627b1/7e617d6c-ebbc-40b2-b398-06ac3d4a7801)

**Comment by SDC-LZC** [comment]
Note: We might change landing page

**Comment by banhpete** [comment]
Grammatical errors corrected despite the possibility that the landing page may change in the future. This is to at least get rid of this error.

See PR https://github.com/Allied-Voices/alliedvoices/pull/87
