### ISSUE TITLE
Change landing page's CTA

### ISSUE THREAD

**Issue by kw496** [Allied-Voices/alliedvoices#90]
Here are some mockups we can go with: 

![1](https://user-images.githubusercontent.com/26206191/118894271-86891480-b8c9-11eb-8cf9-3856bfdec8dd.png)

![2](https://user-images.githubusercontent.com/26206191/118894274-86891480-b8c9-11eb-8569-107afe65ea34.png)

**Comment by banhpete** [comment]
If we automatically go to New York, does that mean we don't want to give the user to search for different locations at all?

**Comment by banhpete** [comment]
User can still search but we will initially sender user to New York.

Landing page has been updated to align with the first design.

See PR https://github.com/Allied-Voices/alliedvoices/pull/103
