### ISSUE TITLE
Drop shadow for reading display

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#92]
Add a drop shadow for the side panel, so that we have more contrast between the side panel and the map:

![Screen Shot 2021-05-19 at 7 17 06 PM](https://user-images.githubusercontent.com/26206191/118900533-cdc9d200-b8d6-11eb-9de2-a7f8e2d663be.png)

**Comment by banhpete** [comment]
Drop shadow added to the reading display.

See PR https://github.com/Allied-Voices/alliedvoices/pull/99

Will review shadow with team and re-open ticket if required.
