### ISSUE TITLE
Pagination at the very bottom of scroll

### ISSUE THREAD

**Issue by SDC-LZC** [Allied-Voices/alliedvoices#93]
![Screen Shot 2021-05-19 at 7 19 16 PM](https://user-images.githubusercontent.com/26206191/118900657-1d100280-b8d7-11eb-8e16-a35589c5ccb2.png)

**Comment by kw496** [comment]
[Look at Airbnb](https://www.airbnb.com/s/Alaska--United-States/homes?refinement_paths%5B%5D=%2Fhomes&tab_id=home_tab&search_type=unknown&flexible_trip_dates%5B%5D=june&flexible_trip_dates%5B%5D=may&flexible_trip_lengths%5B%5D=weekend_trip&date_picker_type=calendar&ne_lat=64.84701483322156&ne_lng=-128.33158748163805&sw_lat=55.87277329222276&sw_lng=-153.99564998163805&zoom=6&search_by_map=true&place_id=ChIJG8CuwJzfAFQRNduKqSde27w) as an example of non-sticky filter + pagination

**Comment by banhpete** [comment]
Filter + pagination no longer sticky

See PR: https://github.com/Allied-Voices/alliedvoices/pull/115
